name: Build Site from Source Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.17.5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: dist
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: github-actions[bot]
          useremail: 41898282+github-actions[bot]@users.noreply.github.com
